version: "3"

services:
  partnership-client:
    build:
      context: ./partnership-client
      dockerfile: client.Dockerfile
    ports:
      - "3000:80"
    mem_limit: 128m
    cpus: ".2"
    env_file:
      - ./partnership-client/.env
    networks:
      - airport-transfer

  guest-client:
    build:
      context: ./guest-client
      dockerfile: client.Dockerfile
    ports:
      - "3002:80"
    mem_limit: 128m
    cpus: ".2"
    env_file:
      - ./guest-client/.env
    networks:
      - airport-transfer

  administration-client:
    build:
      context: ./administration-client
      dockerfile: client.Dockerfile
    ports:
      - "3002:80"
    mem_limit: 128m
    cpus: ".2"
    env_file:
      - ./administration-client/.env
    networks:
      - airport-transfer

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: api-gateway.Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./api-gateway/uploads:/www/var/uploads
    restart: unless-stopped
    mem_limit: 128m
    cpus: ".2"
    networks:
      - airport-transfer
    depends_on:
      - rabbitmq

  user-service:
    build:
      context: ./user-service
      dockerfile: user-service.Dockerfile
    env_file:
      - ./user-service/.env
    restart: unless-stopped
    mem_limit: 128m
    networks:
      - airport-transfer
    depends_on:
      - rabbitmq
      - mssql

  partner-service:
    build:
      context: ./partner-service
      dockerfile: partner-service.Dockerfile
    env_file:
      - ./partner-service/.env
    restart: unless-stopped
    mem_limit: 64m
    cpus: ".2"
    networks:
      - airport-transfer
    depends_on:
      - rabbitmq
      - mssql

  bus-service:
    build:
      context: ./bus-service
      dockerfile: bus-service.Dockerfile
    env_file:
      - ./bus-service/.env
    restart: unless-stopped
    mem_limit: 64m
    cpus: ".2"
    networks:
      - airport-transfer
    depends_on:
      - rabbitmq
      - mssql

  car-service:
    build:
      context: ./car-service
      dockerfile: car-service.Dockerfile
    env_file:
      - ./car-service/.env
    restart: unless-stopped
    mem_limit: 64m
    cpus: ".2"
    networks:
      - airport-transfer
    depends_on:
      - rabbitmq
      - mssql

  train-service:
    build:
      context: ./train-service
      dockerfile: train-service.Dockerfile
    env_file:
      - ./train-service/.env
    restart: unless-stopped
    mem_limit: 64m
    cpus: ".2"
    networks:
      - airport-transfer
    depends_on:
      - rabbitmq
      - mssql

  flight-service:
    build:
      context: ./flight-service
      dockerfile: flight-service.Dockerfile
    env_file:
      - ./flight-service/.env
    restart: unless-stopped
    mem_limit: 64m
    cpus: ".2"
    networks:
      - airport-transfer
    depends_on:
      - rabbitmq
      - mssql

  booking-service:
    build:
      context: ./booking-service
      dockerfile: booking-service.Dockerfile
    env_file:
      - ./booking-service/.env
    restart: unless-stopped
    mem_limit: 64m
    cpus: ".2"
    networks:
      - airport-transfer
    depends_on:
      - rabbitmq
      - mssql

  mssql:
    build:
      context: ./mssql
      dockerfile: mssql.Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123
    volumes:
      - ./database/data:/var/opt/mssql/data
      - ./database/log:/var/opt/mssql/log
      - ./database/secrets:/var/opt/mssql/secrets
    networks:
      - airport-transfer

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - airport-transfer

networks:
  airport-transfer:
    driver: bridge
